### ISSUE TITLE
Link Value

### ISSUE THREAD

**Issue by Basilakis** [appcues/help-scout-widget#5]
Hello,

Could you please help me out, what I should feel here:
return 'http://my-helpscout-proxy.com/feedback';

Thanks a lot!

**Comment by craig-davis** [comment]
Hi @Basilakis. That url is to a proxy script that will accept the form information, and then pass it to the Help Scout API. The proxy script keeps your API token secure. 

We've included a couple of sample proxy scripts in this project, you can find examples for both PHP and Rails here: https://github.com/appcues/help-scout-widget/tree/master/proxies

You'll need to put one of those on your server and then have the javascript widget point to it.
